services:
  animehes:
    build: .
    restart: unless-stopped
    ports:
      - "7100:7100"
    environment:
      HOST: 0.0.0.0
      PORT: 7100
      HENTAILA_BASE_URL: https://hentaila.com
      HENTAILA_CDN_BASE_URL: https://cdn.hentaila.com
      ANIMEAV1_BASE_URL: https://animeav1.com
      ANIMEAV1_CDN_BASE_URL: https://cdn.animeav1.com
      JKANIME_BASE_URL: https://jkanime.net
      METADATA_FALLBACK_BASE_URL: https://94c8cb9f702d-tmdb-addon.baby-beamup.club
      TMDB_API_KEY: ${TMDB_API_KEY:-}
      TMDB_LANGUAGE: ${TMDB_LANGUAGE:-es-ES}
