services:
  - type: web
    name: amokin
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 7100
      - key: HENTAILA_BASE_URL
        value: https://hentaila.com
      - key: HENTAILA_CDN_BASE_URL
        value: https://cdn.hentaila.com
      - key: ANIMEAV1_BASE_URL
        value: https://animeav1.com
      - key: ANIMEAV1_CDN_BASE_URL
        value: https://cdn.animeav1.com
      - key: JKANIME_BASE_URL
        value: https://jkanime.net
      - key: ANIME_MAPPING_BASE_URL
        value: https://animeapi.my.id
      - key: ANILIST_BASE_URL
        value: https://graphql.anilist.co
      - key: METADATA_FALLBACK_BASE_URL
        value: https://94c8cb9f702d-tmdb-addon.baby-beamup.club
      - key: TMDB_LANGUAGE
        value: es-ES
      - key: TMDB_API_KEY
        sync: false
